/// Flutter icons FightProp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FightProp
///      fonts:
///       - asset: fonts/FightProp.ttf
///
///
///
// ignore_for_file: constant_identifier_names, dangling_library_doc_comments

import 'package:flutter/widgets.dart';

class FightProp {
  FightProp._();

  static const _kFontFam = 'FightProp';
  static const String? _kFontPkg = null;

  static const IconData friendship = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cdreduction_primary = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData const_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_attack_percent = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_attack = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_charge_efficiency = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_base_attack = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_critical_hurt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_critical = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_defense_percent = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_defense = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_elec_add_hurt = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_element_mastery = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_fire_add_hurt = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_grass_add_hurt = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_heal_add = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_healed_add = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_hp_percent = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_hp = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_rock_add_hurt = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_physical_add_hurt = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_ice_add_hurt = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_shield_cost_minus_ratio =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_water_add_hurt = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fight_prop_wind_add_hurt = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conscontainer = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_back = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
